openapi: 3.0.0
info:
    title : My secret website
    version : 0.1.9

paths:
    /super_secret/shrek/UwU.php:
        get:
            summary : returns a list of data you can't see
            responses :
                '200':
                    description : A JSON array of data
                    content:
                        application/json:
                            schema:
                                type: array
                                items :
                                    type : string
